### PR TITLE
added a hover popup to open urls

### PR DESCRIPTION
**Pull request by AmjadHD**
added a hover popup to open links, i think this'll be usefull for some people

### CODE REVIEW

**Comment by leonid-shevtsov** [comment]
Thanks! This solves the problem of all mouse bindings being occupied by other actions.

Could you make a new PR (or force-push this one) so that it only contains the new `HoverOpenUrl ` class? I appreciate the formatting, but I'd like to keep things consistent.

**Comment by AmjadHD** [comment]
Do you mean create a new file with only the HoverOpenUrl in it ?

**Comment by AmjadHD** [comment]
or just undo the formatting ?

**Comment by leonid-shevtsov** [comment]
Just undo the formatting, it’s OK to keep it in the same file. Thanks!

**Comment by AmjadHD** [comment]
is that fine ?

**Comment by leonid-shevtsov** [comment]
Yes, thanks!

**Comment by AmjadHD** [comment]
Hi @leonid-shevtsov, it's been a long time since I made this PR, you should merge it cause many users will appreciate the new changes, Thanks.

**Pull request closed without merging**
